seed: 1024
data:
    dataset: anet
    modality: RGB
    num_segments: 8
    seg_length: 1
    batch_size: 32
    workers: 4
    num_classes: 200
    image_tmpl: 'img_{:05d}.jpg'
    # val_root: /bpfs/v2_mnt/VIS/wuwenhao/anet
    #val_root: ../data/ActivityNet_200_sampled/training_resize256x340_fps1
    val_root: ../data/ActivityNet_200_sampled/validation_resize256x340_fps1

    # val_list: 'lists/anet/anet_full_for_zeroshot.txt' # frame_path, num_frames, label
    # val_list: 'lists/anet/anet_sampled_training_zeroshot.txt' # frame_path, num_frames, label
    val_list: 'lists/anet/anet_sampled_validation_zeroshot.txt' # frame_path, num_frames, label

    label_list: 'lists/anet1.3_labels.csv' # label_id, label_name
    index_bias: 1
    input_size: 224
network:
    arch: ViT-L/14 #ViT-L/14 #ViT-B/32 ViT-B/16
    init: True
    drop_out: 0.0 
    emb_dropout: 0.0 
    type: clip_anet
    sim_header: Transf 
logging:
    print_freq: 10
    eval_freq: 5